spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auction
    driver-class-name: org.mariadb.jdbc.Driver
    username: auction
    password: 4223
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup