
server:
  port: 8080

feign:
  okhttp:
    enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auction
    driver-class-name: org.mariadb.jdbc.Driver
    username: auction
    password: 4223
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  redis:
    host: localhost
    port: 6378

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup


  profiles:
    active: default, secret

  quartz:
    scheduler-name: QuartzScheduler
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: QuartzScheduler
      org.quartz.scheduler.instanceId: AUTO

      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 100

      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore